##Artix-7 AC701 Evaluation Platform (xc7a200tfbg676-2)
## Clock and Reset
set_property PACKAGE_PIN R3 [get_ports clk]
set_property IOSTANDARD DIFF_SSTL15 [get_ports clk]
create_clock -period 7 -name clk_50mhz [get_ports clk]
set_property PACKAGE_PIN U4 [get_ports rst_n]
set_property IOSTANDARD LVCMOS15 [get_ports rst_n]

## Control Signals
set_property PACKAGE_PIN P6 [get_ports start]
set_property IOSTANDARD LVCMOS15 [get_ports start]

set_property PACKAGE_PIN M26 [get_ports valid_out]
set_property IOSTANDARD LVCMOS33 [get_ports valid_out]

set_property PACKAGE_PIN T24 [get_ports done]
set_property IOSTANDARD LVCMOS33 [get_ports done]

## Input Samples (x_in_X_real/imag)
# Assigning to available GPIO pins. These are examples and may need adjustment based on actual board availability.
# For simplicity, using a contiguous block of pins. In a real design, these would be carefully chosen.

set_property PACKAGE_PIN G14 [get_ports {x_in_0_real[0]}]
set_property PACKAGE_PIN F14 [get_ports {x_in_0_real[1]}]
set_property PACKAGE_PIN E14 [get_ports {x_in_0_real[2]}]
set_property PACKAGE_PIN D14 [get_ports {x_in_0_real[3]}]
set_property PACKAGE_PIN C14 [get_ports {x_in_0_real[4]}]
set_property PACKAGE_PIN B14 [get_ports {x_in_0_real[5]}]
set_property PACKAGE_PIN A14 [get_ports {x_in_0_real[6]}]
set_property PACKAGE_PIN G13 [get_ports {x_in_0_real[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_in_0_real[*]}]

set_property PACKAGE_PIN F13 [get_ports {x_in_0_imag[0]}]
set_property PACKAGE_PIN E13 [get_ports {x_in_0_imag[1]}]
set_property PACKAGE_PIN D13 [get_ports {x_in_0_imag[2]}]
set_property PACKAGE_PIN C13 [get_ports {x_in_0_imag[3]}]
set_property PACKAGE_PIN B13 [get_ports {x_in_0_imag[4]}]
set_property PACKAGE_PIN A13 [get_ports {x_in_0_imag[5]}]
set_property PACKAGE_PIN G12 [get_ports {x_in_0_imag[6]}]
set_property PACKAGE_PIN F12 [get_ports {x_in_0_imag[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_in_0_imag[*]}]

set_property PACKAGE_PIN E12 [get_ports {x_in_1_real[0]}]
set_property PACKAGE_PIN D12 [get_ports {x_in_1_real[1]}]
set_property PACKAGE_PIN C12 [get_ports {x_in_1_real[2]}]
set_property PACKAGE_PIN B12 [get_ports {x_in_1_real[3]}]
set_property PACKAGE_PIN A12 [get_ports {x_in_1_real[4]}]
set_property PACKAGE_PIN G11 [get_ports {x_in_1_real[5]}]
set_property PACKAGE_PIN F11 [get_ports {x_in_1_real[6]}]
set_property PACKAGE_PIN E11 [get_ports {x_in_1_real[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_in_1_real[*]}]

set_property PACKAGE_PIN D11 [get_ports {x_in_1_imag[0]}]
set_property PACKAGE_PIN C11 [get_ports {x_in_1_imag[1]}]
set_property PACKAGE_PIN B11 [get_ports {x_in_1_imag[2]}]
set_property PACKAGE_PIN A11 [get_ports {x_in_1_imag[3]}]
set_property PACKAGE_PIN G10 [get_ports {x_in_1_imag[4]}]
set_property PACKAGE_PIN F10 [get_ports {x_in_1_imag[5]}]
set_property PACKAGE_PIN E10 [get_ports {x_in_1_imag[6]}]
set_property PACKAGE_PIN D10 [get_ports {x_in_1_imag[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_in_1_imag[*]}]

set_property PACKAGE_PIN C10 [get_ports {x_in_2_real[0]}]
set_property PACKAGE_PIN B10 [get_ports {x_in_2_real[1]}]
set_property PACKAGE_PIN A10 [get_ports {x_in_2_real[2]}]
set_property PACKAGE_PIN G9 [get_ports {x_in_2_real[3]}]
set_property PACKAGE_PIN F9 [get_ports {x_in_2_real[4]}]
set_property PACKAGE_PIN E9 [get_ports {x_in_2_real[5]}]
set_property PACKAGE_PIN D9 [get_ports {x_in_2_real[6]}]
set_property PACKAGE_PIN C9 [get_ports {x_in_2_real[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_in_2_real[*]}]

set_property PACKAGE_PIN B9 [get_ports {x_in_2_imag[0]}]
set_property PACKAGE_PIN A9 [get_ports {x_in_2_imag[1]}]
set_property PACKAGE_PIN G8 [get_ports {x_in_2_imag[2]}]
set_property PACKAGE_PIN F8 [get_ports {x_in_2_imag[3]}]
set_property PACKAGE_PIN E8 [get_ports {x_in_2_imag[4]}]
set_property PACKAGE_PIN D8 [get_ports {x_in_2_imag[5]}]
set_property PACKAGE_PIN C8 [get_ports {x_in_2_imag[6]}]
set_property PACKAGE_PIN B8 [get_ports {x_in_2_imag[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_in_2_imag[*]}]

set_property PACKAGE_PIN A8 [get_ports {x_in_3_real[0]}]
set_property PACKAGE_PIN G7 [get_ports {x_in_3_real[1]}]
set_property PACKAGE_PIN F7 [get_ports {x_in_3_real[2]}]
set_property PACKAGE_PIN E7 [get_ports {x_in_3_real[3]}]
set_property PACKAGE_PIN D7 [get_ports {x_in_3_real[4]}]
set_property PACKAGE_PIN C7 [get_ports {x_in_3_real[5]}]
set_property PACKAGE_PIN B7 [get_ports {x_in_3_real[6]}]
set_property PACKAGE_PIN A7 [get_ports {x_in_3_real[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_in_3_real[*]}]

set_property PACKAGE_PIN G6 [get_ports {x_in_3_imag[0]}]
set_property PACKAGE_PIN F6 [get_ports {x_in_3_imag[1]}]
set_property PACKAGE_PIN E6 [get_ports {x_in_3_imag[2]}]
set_property PACKAGE_PIN D6 [get_ports {x_in_3_imag[3]}]
set_property PACKAGE_PIN C6 [get_ports {x_in_3_imag[4]}]
set_property PACKAGE_PIN B6 [get_ports {x_in_3_imag[5]}]
set_property PACKAGE_PIN A6 [get_ports {x_in_3_imag[6]}]
set_property PACKAGE_PIN G5 [get_ports {x_in_3_imag[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_in_3_imag[*]}]

set_property PACKAGE_PIN F5 [get_ports {x_in_4_real[0]}]
set_property PACKAGE_PIN E5 [get_ports {x_in_4_real[1]}]
set_property PACKAGE_PIN D5 [get_ports {x_in_4_real[2]}]
set_property PACKAGE_PIN C5 [get_ports {x_in_4_real[3]}]
set_property PACKAGE_PIN B5 [get_ports {x_in_4_real[4]}]
set_property PACKAGE_PIN A5 [get_ports {x_in_4_real[5]}]
set_property PACKAGE_PIN G4 [get_ports {x_in_4_real[6]}]
set_property PACKAGE_PIN F4 [get_ports {x_in_4_real[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_in_4_real[*]}]

set_property PACKAGE_PIN E4 [get_ports {x_in_4_imag[0]}]
set_property PACKAGE_PIN D4 [get_ports {x_in_4_imag[1]}]
set_property PACKAGE_PIN C4 [get_ports {x_in_4_imag[2]}]
set_property PACKAGE_PIN B4 [get_ports {x_in_4_imag[3]}]
set_property PACKAGE_PIN A4 [get_ports {x_in_4_imag[4]}]
set_property PACKAGE_PIN G3 [get_ports {x_in_4_imag[5]}]
set_property PACKAGE_PIN F3 [get_ports {x_in_4_imag[6]}]
set_property PACKAGE_PIN E3 [get_ports {x_in_4_imag[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_in_4_imag[*]}]

set_property PACKAGE_PIN D3 [get_ports {x_in_5_real[0]}]
set_property PACKAGE_PIN C3 [get_ports {x_in_5_real[1]}]
set_property PACKAGE_PIN B3 [get_ports {x_in_5_real[2]}]
set_property PACKAGE_PIN A3 [get_ports {x_in_5_real[3]}]
set_property PACKAGE_PIN G2 [get_ports {x_in_5_real[4]}]
set_property PACKAGE_PIN F2 [get_ports {x_in_5_real[5]}]
set_property PACKAGE_PIN E2 [get_ports {x_in_5_real[6]}]
set_property PACKAGE_PIN D2 [get_ports {x_in_5_real[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_in_5_real[*]}]

set_property PACKAGE_PIN C2 [get_ports {x_in_5_imag[0]}]
set_property PACKAGE_PIN B2 [get_ports {x_in_5_imag[1]}]
set_property PACKAGE_PIN A2 [get_ports {x_in_5_imag[2]}]
set_property PACKAGE_PIN G1 [get_ports {x_in_5_imag[3]}]
set_property PACKAGE_PIN F1 [get_ports {x_in_5_imag[4]}]
set_property PACKAGE_PIN E1 [get_ports {x_in_5_imag[5]}]
set_property PACKAGE_PIN D1 [get_ports {x_in_5_imag[6]}]
set_property PACKAGE_PIN C1 [get_ports {x_in_5_imag[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_in_5_imag[*]}]

set_property PACKAGE_PIN B1 [get_ports {x_in_6_real[0]}]
set_property PACKAGE_PIN A1 [get_ports {x_in_6_real[1]}]
set_property PACKAGE_PIN G26 [get_ports {x_in_6_real[2]}]
set_property PACKAGE_PIN F26 [get_ports {x_in_6_real[3]}]
set_property PACKAGE_PIN E26 [get_ports {x_in_6_real[4]}]
set_property PACKAGE_PIN D26 [get_ports {x_in_6_real[5]}]
set_property PACKAGE_PIN C26 [get_ports {x_in_6_real[6]}]
set_property PACKAGE_PIN B26 [get_ports {x_in_6_real[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_in_6_real[*]}]

set_property PACKAGE_PIN A26 [get_ports {x_in_6_imag[0]}]
set_property PACKAGE_PIN G25 [get_ports {x_in_6_imag[1]}]
set_property PACKAGE_PIN F25 [get_ports {x_in_6_imag[2]}]
set_property PACKAGE_PIN E25 [get_ports {x_in_6_imag[3]}]
set_property PACKAGE_PIN D25 [get_ports {x_in_6_imag[4]}]
set_property PACKAGE_PIN C25 [get_ports {x_in_6_imag[5]}]
set_property PACKAGE_PIN B25 [get_ports {x_in_6_imag[6]}]
set_property PACKAGE_PIN A25 [get_ports {x_in_6_imag[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_in_6_imag[*]}]

set_property PACKAGE_PIN G24 [get_ports {x_in_7_real[0]}]
set_property PACKAGE_PIN F24 [get_ports {x_in_7_real[1]}]
set_property PACKAGE_PIN E24 [get_ports {x_in_7_real[2]}]
set_property PACKAGE_PIN D24 [get_ports {x_in_7_real[3]}]
set_property PACKAGE_PIN C24 [get_ports {x_in_7_real[4]}]
set_property PACKAGE_PIN B24 [get_ports {x_in_7_real[5]}]
set_property PACKAGE_PIN A24 [get_ports {x_in_7_real[6]}]
set_property PACKAGE_PIN G23 [get_ports {x_in_7_real[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_in_7_real[*]}]

set_property PACKAGE_PIN F23 [get_ports {x_in_7_imag[0]}]
set_property PACKAGE_PIN E23 [get_ports {x_in_7_imag[1]}]
set_property PACKAGE_PIN D23 [get_ports {x_in_7_imag[2]}]
set_property PACKAGE_PIN C23 [get_ports {x_in_7_imag[3]}]
set_property PACKAGE_PIN B23 [get_ports {x_in_7_imag[4]}]
set_property PACKAGE_PIN A23 [get_ports {x_in_7_imag[5]}]
set_property PACKAGE_PIN G22 [get_ports {x_in_7_imag[6]}]
set_property PACKAGE_PIN F22 [get_ports {x_in_7_imag[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_in_7_imag[*]}]

## Output Samples (x_out_X_real/imag)
# Assigning to available GPIO pins. These are examples and may need adjustment based on actual board availability.

set_property PACKAGE_PIN E22 [get_ports {x_out_0_real[0]}]
set_property PACKAGE_PIN D22 [get_ports {x_out_0_real[1]}]
set_property PACKAGE_PIN C22 [get_ports {x_out_0_real[2]}]
set_property PACKAGE_PIN B22 [get_ports {x_out_0_real[3]}]
set_property PACKAGE_PIN A22 [get_ports {x_out_0_real[4]}]
set_property PACKAGE_PIN G21 [get_ports {x_out_0_real[5]}]
set_property PACKAGE_PIN F21 [get_ports {x_out_0_real[6]}]
set_property PACKAGE_PIN E21 [get_ports {x_out_0_real[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_out_0_real[*]}]

set_property PACKAGE_PIN D21 [get_ports {x_out_0_imag[0]}]
set_property PACKAGE_PIN C21 [get_ports {x_out_0_imag[1]}]
set_property PACKAGE_PIN B21 [get_ports {x_out_0_imag[2]}]
set_property PACKAGE_PIN A21 [get_ports {x_out_0_imag[3]}]
set_property PACKAGE_PIN G20 [get_ports {x_out_0_imag[4]}]
set_property PACKAGE_PIN F20 [get_ports {x_out_0_imag[5]}]
set_property PACKAGE_PIN E20 [get_ports {x_out_0_imag[6]}]
set_property PACKAGE_PIN D20 [get_ports {x_out_0_imag[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_out_0_imag[*]}]

set_property PACKAGE_PIN C20 [get_ports {x_out_1_real[0]}]
set_property PACKAGE_PIN B20 [get_ports {x_out_1_real[1]}]
set_property PACKAGE_PIN A20 [get_ports {x_out_1_real[2]}]
set_property PACKAGE_PIN G19 [get_ports {x_out_1_real[3]}]
set_property PACKAGE_PIN F19 [get_ports {x_out_1_real[4]}]
set_property PACKAGE_PIN E19 [get_ports {x_out_1_real[5]}]
set_property PACKAGE_PIN D19 [get_ports {x_out_1_real[6]}]
set_property PACKAGE_PIN C19 [get_ports {x_out_1_real[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_out_1_real[*]}]

set_property PACKAGE_PIN B19 [get_ports {x_out_1_imag[0]}]
set_property PACKAGE_PIN A19 [get_ports {x_out_1_imag[1]}]
set_property PACKAGE_PIN G18 [get_ports {x_out_1_imag[2]}]
set_property PACKAGE_PIN F18 [get_ports {x_out_1_imag[3]}]
set_property PACKAGE_PIN E18 [get_ports {x_out_1_imag[4]}]
set_property PACKAGE_PIN D18 [get_ports {x_out_1_imag[5]}]
set_property PACKAGE_PIN C18 [get_ports {x_out_1_imag[6]}]
set_property PACKAGE_PIN B18 [get_ports {x_out_1_imag[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_out_1_imag[*]}]

set_property PACKAGE_PIN A18 [get_ports {x_out_2_real[0]}]
set_property PACKAGE_PIN G17 [get_ports {x_out_2_real[1]}]
set_property PACKAGE_PIN F17 [get_ports {x_out_2_real[2]}]
set_property PACKAGE_PIN E17 [get_ports {x_out_2_real[3]}]
set_property PACKAGE_PIN D17 [get_ports {x_out_2_real[4]}]
set_property PACKAGE_PIN C17 [get_ports {x_out_2_real[5]}]
set_property PACKAGE_PIN B17 [get_ports {x_out_2_real[6]}]
set_property PACKAGE_PIN A17 [get_ports {x_out_2_real[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_out_2_real[*]}]

set_property PACKAGE_PIN G16 [get_ports {x_out_2_imag[0]}]
set_property PACKAGE_PIN F16 [get_ports {x_out_2_imag[1]}]
set_property PACKAGE_PIN E16 [get_ports {x_out_2_imag[2]}]
set_property PACKAGE_PIN D16 [get_ports {x_out_2_imag[3]}]
set_property PACKAGE_PIN C16 [get_ports {x_out_2_imag[4]}]
set_property PACKAGE_PIN B16 [get_ports {x_out_2_imag[5]}]
set_property PACKAGE_PIN A16 [get_ports {x_out_2_imag[6]}]
set_property PACKAGE_PIN G15 [get_ports {x_out_2_imag[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_out_2_imag[*]}]

set_property PACKAGE_PIN F15 [get_ports {x_out_3_real[0]}]
set_property PACKAGE_PIN E15 [get_ports {x_out_3_real[1]}]
set_property PACKAGE_PIN D15 [get_ports {x_out_3_real[2]}]
set_property PACKAGE_PIN C15 [get_ports {x_out_3_real[3]}]
set_property PACKAGE_PIN B15 [get_ports {x_out_3_real[4]}]
set_property PACKAGE_PIN A15 [get_ports {x_out_3_real[5]}]
set_property PACKAGE_PIN G14 [get_ports {x_out_3_real[6]}]
set_property PACKAGE_PIN F14 [get_ports {x_out_3_real[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_out_3_real[*]}]

set_property PACKAGE_PIN E14 [get_ports {x_out_3_imag[0]}]
set_property PACKAGE_PIN D14 [get_ports {x_out_3_imag[1]}]
set_property PACKAGE_PIN C14 [get_ports {x_out_3_imag[2]}]
set_property PACKAGE_PIN B14 [get_ports {x_out_3_imag[3]}]
set_property PACKAGE_PIN A14 [get_ports {x_out_3_imag[4]}]
set_property PACKAGE_PIN G13 [get_ports {x_out_3_imag[5]}]
set_property PACKAGE_PIN F13 [get_ports {x_out_3_imag[6]}]
set_property PACKAGE_PIN E13 [get_ports {x_out_3_imag[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_out_3_imag[*]}]

set_property PACKAGE_PIN D13 [get_ports {x_out_4_real[0]}]
set_property PACKAGE_PIN C13 [get_ports {x_out_4_real[1]}]
set_property PACKAGE_PIN B13 [get_ports {x_out_4_real[2]}]
set_property PACKAGE_PIN A13 [get_ports {x_out_4_real[3]}]
set_property PACKAGE_PIN G12 [get_ports {x_out_4_real[4]}]
set_property PACKAGE_PIN F12 [get_ports {x_out_4_real[5]}]
set_property PACKAGE_PIN E12 [get_ports {x_out_4_real[6]}]
set_property PACKAGE_PIN D12 [get_ports {x_out_4_real[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_out_4_real[*]}]

set_property PACKAGE_PIN C12 [get_ports {x_out_4_imag[0]}]
set_property PACKAGE_PIN B12 [get_ports {x_out_4_imag[1]}]
set_property PACKAGE_PIN A12 [get_ports {x_out_4_imag[2]}]
set_property PACKAGE_PIN G11 [get_ports {x_out_4_imag[3]}]
set_property PACKAGE_PIN F11 [get_ports {x_out_4_imag[4]}]
set_property PACKAGE_PIN E11 [get_ports {x_out_4_imag[5]}]
set_property PACKAGE_PIN D11 [get_ports {x_out_4_imag[6]}]
set_property PACKAGE_PIN C11 [get_ports {x_out_4_imag[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_out_4_imag[*]}]

set_property PACKAGE_PIN B11 [get_ports {x_out_5_real[0]}]
set_property PACKAGE_PIN A11 [get_ports {x_out_5_real[1]}]
set_property PACKAGE_PIN G10 [get_ports {x_out_5_real[2]}]
set_property PACKAGE_PIN F10 [get_ports {x_out_5_real[3]}]
set_property PACKAGE_PIN E10 [get_ports {x_out_5_real[4]}]
set_property PACKAGE_PIN D10 [get_ports {x_out_5_real[5]}]
set_property PACKAGE_PIN C10 [get_ports {x_out_5_real[6]}]
set_property PACKAGE_PIN B10 [get_ports {x_out_5_real[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_out_5_real[*]}]

set_property PACKAGE_PIN A10 [get_ports {x_out_5_imag[0]}]
set_property PACKAGE_PIN G9 [get_ports {x_out_5_imag[1]}]
set_property PACKAGE_PIN F9 [get_ports {x_out_5_imag[2]}]
set_property PACKAGE_PIN E9 [get_ports {x_out_5_imag[3]}]
set_property PACKAGE_PIN D9 [get_ports {x_out_5_imag[4]}]
set_property PACKAGE_PIN C9 [get_ports {x_out_5_imag[5]}]
set_property PACKAGE_PIN B9 [get_ports {x_out_5_imag[6]}]
set_property PACKAGE_PIN A9 [get_ports {x_out_5_imag[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_out_5_imag[*]}]

set_property PACKAGE_PIN G8 [get_ports {x_out_6_real[0]}]
set_property PACKAGE_PIN F8 [get_ports {x_out_6_real[1]}]
set_property PACKAGE_PIN E8 [get_ports {x_out_6_real[2]}]
set_property PACKAGE_PIN D8 [get_ports {x_out_6_real[3]}]
set_property PACKAGE_PIN C8 [get_ports {x_out_6_real[4]}]
set_property PACKAGE_PIN B8 [get_ports {x_out_6_real[5]}]
set_property PACKAGE_PIN A8 [get_ports {x_out_6_real[6]}]
set_property PACKAGE_PIN G7 [get_ports {x_out_6_real[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_out_6_real[*]}]

set_property PACKAGE_PIN F7 [get_ports {x_out_6_imag[0]}]
set_property PACKAGE_PIN E7 [get_ports {x_out_6_imag[1]}]
set_property PACKAGE_PIN D7 [get_ports {x_out_6_imag[2]}]
set_property PACKAGE_PIN C7 [get_ports {x_out_6_imag[3]}]
set_property PACKAGE_PIN B7 [get_ports {x_out_6_imag[4]}]
set_property PACKAGE_PIN A7 [get_ports {x_out_6_imag[5]}]
set_property PACKAGE_PIN G6 [get_ports {x_out_6_imag[6]}]
set_property PACKAGE_PIN F6 [get_ports {x_out_6_imag[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_out_6_imag[*]}]

set_property PACKAGE_PIN E6 [get_ports {x_out_7_real[0]}]
set_property PACKAGE_PIN D6 [get_ports {x_out_7_real[1]}]
set_property PACKAGE_PIN C6 [get_ports {x_out_7_real[2]}]
set_property PACKAGE_PIN B6 [get_ports {x_out_7_real[3]}]
set_property PACKAGE_PIN A6 [get_ports {x_out_7_real[4]}]
set_property PACKAGE_PIN G5 [get_ports {x_out_7_real[5]}]
set_property PACKAGE_PIN F5 [get_ports {x_out_7_real[6]}]
set_property PACKAGE_PIN E5 [get_ports {x_out_7_real[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_out_7_real[*]}]

set_property PACKAGE_PIN D5 [get_ports {x_out_7_imag[0]}]
set_property PACKAGE_PIN C5 [get_ports {x_out_7_imag[1]}]
set_property PACKAGE_PIN B5 [get_ports {x_out_7_imag[2]}]
set_property PACKAGE_PIN A5 [get_ports {x_out_7_imag[3]}]
set_property PACKAGE_PIN G4 [get_ports {x_out_7_imag[4]}]
set_property PACKAGE_PIN F4 [get_ports {x_out_7_imag[5]}]
set_property PACKAGE_PIN E4 [get_ports {x_out_7_imag[6]}]
set_property PACKAGE_PIN D4 [get_ports {x_out_7_imag[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_out_7_imag[*]}]




set_property PACKAGE_PIN E6 [get_ports {x_out_7_real[0]}]
set_property PACKAGE_PIN D6 [get_ports {x_out_7_real[1]}]
set_property PACKAGE_PIN C6 [get_ports {x_out_7_real[2]}]
set_property PACKAGE_PIN B6 [get_ports {x_out_7_real[3]}]
set_property PACKAGE_PIN A6 [get_ports {x_out_7_real[4]}]
set_property PACKAGE_PIN G5 [get_ports {x_out_7_real[5]}]
set_property PACKAGE_PIN F5 [get_ports {x_out_7_real[6]}]
set_property PACKAGE_PIN E5 [get_ports {x_out_7_real[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_out_7_real[*]}]

set_property PACKAGE_PIN D5 [get_ports {x_out_7_imag[0]}]
set_property PACKAGE_PIN C5 [get_ports {x_out_7_imag[1]}]
set_property PACKAGE_PIN B5 [get_ports {x_out_7_imag[2]}]
set_property PACKAGE_PIN A5 [get_ports {x_out_7_imag[3]}]
set_property PACKAGE_PIN G4 [get_ports {x_out_7_imag[4]}]
set_property PACKAGE_PIN F4 [get_ports {x_out_7_imag[5]}]
set_property PACKAGE_PIN E4 [get_ports {x_out_7_imag[6]}]
set_property PACKAGE_PIN D4 [get_ports {x_out_7_imag[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x_out_7_imag[*]}]


